services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./models:/app/models
    env_file:
      - path: .env
        required: false
    ports:
      - "${MATRIX_PORT:-5000}:${MATRIX_PORT:-5000}"
    tty: true
    stdin_open: true
